# Generated by Django 5.1.2 on 2025-03-17 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuizApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='correct_answer',
            field=models.CharField(choices=[('A', 'option_a'), ('B', 'option_b'), ('C', 'option_c'), ('D', 'option_d')], default='A', max_length=1),
        ),
    ]
