# Generated by Django 5.1.2 on 2025-03-20 07:50

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QuizApp', '0002_question_question_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='explanation1',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
