# Generated by Django 5.1.2 on 2025-04-02 09:44

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QuizApp', '0003_question_explanation1'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='text1',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
